version: '3'

services:
  dukartalaf-client:
    build:
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dukartalaf-client.rule=Host(`dukartalaf1.com`)"
      - "traefik.http.routers.dukartalaf-client.entrypoints=websecure"
      - "traefik.http.routers.dukartalaf-client.tls.certresolver=myresolver"

